version = "v0.1.0"

[[messages]]
role = "system"
content = """
You are a data visualization expert specializing in pattern classification.
Your task is to analyze user queries and data characteristics to select
the most appropriate visualization pattern from a predefined 3x3 matrix.
Focus on understanding the user's intent and matching it with data capabilities.
"""
do_strip = true

[[messages]]
role = "user"
content = """
## Visualization Pattern Definitions

Visualization patterns are organized in a 3x3 matrix:

### Primary Intent (rows):
- Transition: Show changes over time
- Difference: Compare between categories
- Overview: Show distribution or composition

### Secondary Intent (columns):
- None: Single intent only
- Transition: Add time aspect
- Difference: Add comparison aspect
- Overview: Add distribution aspect

### The 9 patterns:
- P01 (Transition only): Single time series trend
- P02 (Difference only): Category comparison
- P03 (Overview only): Distribution or composition
- P12 (Transition + Difference): Multiple time series comparison
- P13 (Transition + Overview): Distribution changes over time
- P21 (Difference + Transition): Category differences over time
- P23 (Difference + Overview): Category-wise distribution comparison
- P31 (Overview + Transition): Overall picture changes over time
- P32 (Overview + Difference): Distribution comparison between categories

## Examples

Query: "Show monthly sales trend"
Data: Has date column, numeric sales column
Pattern: P01 (single time series)

Query: "Compare revenue by region"
Data: Has region categories, revenue values
Pattern: P02 (category comparison)

Query: "Show how customer age distribution changed over years"
Data: Has age values, year column
Pattern: P13 (distribution over time)

Query: "Compare product sales trends across categories"
Data: Has dates, categories, sales values
Pattern: P12 (multiple time series comparison)

## Task

Select the most appropriate visualization pattern for the following:

User Query: "{{ query }}"

Data Characteristics:
{{ data_info }}

## Instructions
1. Analyze the user's intent from the query
2. Consider the data characteristics
3. Select exactly ONE pattern from P01, P02, P03, P12, P13, P21, P23, P31, P32
4. Provide your reasoning

Respond in JSON format:
{
    "pattern_id": "P01",  // One of: P01, P02, P03, P12, P13, P21, P23, P31, P32
    "reasoning": "Brief explanation of why this pattern fits",
    "confidence": 0.95  // Confidence score between 0 and 1
}
"""
do_strip = true
